name: base
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.8
  - ipython
  - pip
  - pip:
    - aiohttp
    - git+https://github.com/filipinascimento/fury.git@feature_fury_stream_client
